### ISSUE TITLE
بلاک شدن پیام های iMessage

### ISSUE THREAD

**Issue by BloodhoundAllfather** [hiddify/Hiddify-Manager#3540]
سلام
من هیدیفای رو با یک دامین راه انداختم. همه چیز خوبه ولی پیام های iMessage از طریق VPN نمیره. باید VPN رو قطع کنم تا پیام ها دلیور بشه.
میدونید دلیلش چیه؟ کس دیگه ای این مشکل رو داره؟

من از v2box استفاده میکنم ولی foXray هم همینه. فرقی نداره

**Comment by robin98** [comment]
Try streisand app and let me know if it helps.

**Comment by BloodhoundAllfather** [comment]
> Try streisand app and let me know if it helps.

It actually worked! Thank you. Now I'm curious to know what's the reason behind it.

**Comment by robin98** [comment]
> > Try streisand app and let me know if it helps.
> 
> It actually worked! Thank you. Now I'm curious to know what's the reason behind it.

There are plenty of possibilities around it.
Maybe that was because of the DNS handling system, background activity management of the app etc…
I suggest you to remove the v2box app and try a fresh installation. Also keep in mind that v2box add “Apple on direct” option, under the routing settings; so maybe you wanna give it a try. This will try for bypassing all the system-related traffic and route them through your original IP.
