### ISSUE TITLE
api v2 can not get specific uuid

### ISSUE THREAD

**Issue by MeysamFallah** [hiddify/Hiddify-Manager#4100]
in new api v2, the "/{proxy_path}/api/v2/admin/user/{uuid}/" url can not return the specific user detail by **uuid** and get error "user not found".
I'm sure the uuid I put in the api is correct, While the api without uuid returns the complete list of users correctly.

**Comment by Iam54r1n4** [comment]
We're working on the APIs bug, which will be fixed in the next update.

**Comment by iegl3** [comment]
> We're working on the APIs bug, which will be fixed in the next update.

is it not fixed yet?

**Comment by Iam54r1n4** [comment]
> > We're working on the APIs bug, which will be fixed in the next update.
> 
> is it not fixed yet?

Hi, I no longer work on this project, and I believed the issue had been fixed by now, but you can view the API's endpoint bindings here:
[__ init __.py](https://github.com/hiddify/HiddifyPanel/blob/64f419619458847a2f4c22176e4312f7a22a80d6/hiddifypanel/panel/commercial/restapi/v2/admin/__init__.py#L26)

As you can see, the URL you mentioned is bound to the UserApi class. Ok WTF is UserApi?:
[User API Link](https://github.com/hiddify/HiddifyPanel/blob/64f419619458847a2f4c22176e4312f7a22a80d6/hiddifypanel/panel/commercial/restapi/v2/admin/user_api.py#L16)

The UserApi class is responsible for the .../user/{UUID}/ endpoint, and its methods (get, patch, and delete) handle the various HTTP methods associated with this endpoint.

So when you make a GET request to the .../user/{UUID} endpoint, your request is processed by the get method of the UserApi class:
[UserApi get](https://github.com/hiddify/HiddifyPanel/blob/64f419619458847a2f4c22176e4312f7a22a80d6/hiddifypanel/panel/commercial/restapi/v2/admin/user_api.py#L19)


I don't know what you want to do, but IMO, it would be better if you go ahead and debug the issue yourself. The last commit on the panel is from a month ago, so it is unlikely that anyone will address your report.
