### ISSUE TITLE
error patching outbound[National § 0][custom]: netip,ParsePrefix("/24"):ParseAddr(""): unable to parse lP

### ISSUE THREAD

**Issue by jingcard** [hiddify/Hiddify-Manager#4207]
new configuration file:  +Add Warp   Hiddify WARP 
error patching outbound[National § 0][custom]: netip,ParsePrefix("/24"):ParseAddr(""): unable to parse lP

**Comment by Vh42510** [comment]
I have the same problem, is there a solution?

**Comment by Vh42510** [comment]
![Screenshot 2024-07-15 125924](https://github.com/user-attachments/assets/1823fa08-176b-45a1-9821-d735a0bfeeec)

**Comment by arianfar62** [comment]
درود بر شما
از طریف + در بالا وارپ اضافه کنید. سپس وارپ را فعال کنید. بعد از فعالسازی وارپ، از طریق تنظیمات پیکربندی، ایجاد پیکربندی وارپ را بزنید تاپیکربندی ایجاد و مشکل حل شود.
درصورتی که باز هم مشکل داشتید از طریق سه کلید ALT+CTRL+DEL فقط وارپ کلاینت را End Task کنید و دوباره افزودن پروفایل وارپ را بزنید.
سلامتی شما و همه ام آرزوست

**Comment by MrCat37** [comment]
I figured out how to solve this problem. It's a pretty complicated problem, I warn you. It occurred to me when I was reinstalling the app to a newer version. To solve it, you need to reinstall the app from scratch. But the problem is that after you uninstall the app, it leaves behind a tail of residual files. To remove them, you either need special software, which I didn't have, or type hiddify in the search: "this computer" and delete all files from this program.
