### ISSUE TITLE
ShadowTLS doesn't work

### ISSUE THREAD

**Issue by BloodhoundAllfather** [hiddify/Hiddify-Manager#4604]
I installed v10.70.0, configured my server with DNS and enabled ShadowTLS. But when I click on a user to grab ShadowTLS link, the link is this text: **"ShadowTLS is Not Supported for this platform"**

I have these proxies enabled: ShadowTSL, VLESS, Trojan, TCP, h2 and XRay Full Config Link

My server is Ubuntu 22.04 LTS

Do you have any idea what I'm doing wrong? This option used to work for me in the past

Thank you

P.S. Any answer in any language is appreciated

**Comment by blshkv** [comment]
Hello, I would like to follow up on this.

So the "auto" option is great, but it would choose from all available configs below, would it?
And since ShadowTLS is "not supported for this platform" it would never be used.

Am I correct? If yes, how to fix ShadowTLS and provide this additional option to users?

Platform: Ubuntu

Thank you.
